name: Update application
run-name: Update application
on: [workflow_dispatch]
env:
  SOURCES_PATH: .sources
jobs:
  Update-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out application
        uses: actions/checkout@v3
      - name: Check out sources
        uses: actions/checkout@v3
        with:
          repository: rybick/pogolitics
          path: './.sources'
      - name: Build sources
        run: >
             cd "${{ github.workspace }}/$SOURCES_PATH" &&
             ls && 
             ./gradlew clean build &&
             ls -la
      - name: Copy built application to main directory
        run: >
             ls -la &&
             rm -r ./* &&
             git checkout README.md && echo "#We don't want to lose README" &&
             ls &&
             ls ${{ github.workspace }}/$SOURCES_PATH/ &&
             cp -r ${{ github.workspace }}/$SOURCES_PATH/build/distributions/* ./
      - uses: EndBug/add-and-commit@v9
        with:
          message: update version (github actions)